image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependencies & Database
    init: |
      psql --command="CREATE USER scheduler PASSWORD 'somestrong'"
      psql --command="CREATE DATABASE timetable OWNER scheduler "
    command: PGPASSWORD=somestrong psql --username=scheduler --host=localhost --dbname=timetable -c "SELECT version()"

  - name: Golang tools
    command: go get -u github.com/rakyll/gotest


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
