version: 2

before:
  hooks:
    - go mod download
    # - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows

archives:
- name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - samples/*.sql
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


nfpms:
  # note that this is an array of nfpm configs
  -
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    vendor: CYBERTEC PostgreSQL International GmbH
    homepage: https://www.cybertec-postgresql.com/en/products/pg_timetable/

    maintainer: Pavlo Golub <pavlo.golub@cybertec.at>
    description: pg_timetable - Advanced scheduling for PostgreSQL

    license: MIT Licence

    # Formats to be generated.
    formats:
      - deb
      - rpm
