before:
  hooks:
    - go mod download
    # - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows

  # ignore:
  #   - goos: darwin
  #     goarch: 386
  #   - goos: windows
  #     goarch: 386
  #   - goos: windows
  #     goarch: arm64 

archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  wrap_in_directory: true
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - samples/*.sql
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


nfpms:
  # note that this is an array of nfpm configs
  -

    # Replacements for GOOS and GOARCH in the package name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    vendor: Cybertec Schönig & Schönig GmbH
    homepage: https://www.cybertec-postgresql.com/en/products/pg_timetable/

    maintainer: Pavlo Golub <pavlo.golub@cybertec.at>
    description: pg_timetable - Advanced scheduling for PostgreSQL

    license: MIT Licence

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Files to add to your package (beyond the binary).
    # Keys are source paths/globs to get the files from.
    # Values are the destination locations of the files in the package.
    # Use globs to add all contents of a folder.
    # files:
    #   "scripts/etc/init.d/**": "/etc/init.d"
    #   "path/**/glob": "/var/foo/glob"