before:
  hooks:
    - go mod download
    # - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE.txt
    - README.md
    - sql/*.sql
    - samples/*.sql
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'