{
 "title": "Timetable overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client name",
    "query": "SELECT DISTINCT(l.client_name) FROM timetable.log l "
   }
  ]
 },
 "panels": [
  {
   "title": "Total Chains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  timetable.chain\n\n"
    }
   ]
  },
  {
   "title": "Enabled Chains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  timetable.chain\nWHERE\n  live and client_name ISNULL or client_name in ($client) "
    }
   ]
  },
  {
   "title": "Total task executions",
   "type": "stat",
   "description": "How many tasks executed during selected interval",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  timetable.execution_log\nWHERE\n  $__timeFilter(last_run) and client_name in ($client) "
    }
   ]
  },
  {
   "title": "Total task errors",
   "type": "stat",
   "description": "How many tasks failed during selected interval",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  timetable.execution_log\nWHERE\n  $__timeFilter(last_run)\n  AND returncode != 0 AND NOT COALESCE(ignore_error, false) AND client_name in ($client) "
    }
   ]
  },
  {
   "title": "Avg. task duration",
   "type": "stat",
   "description": "Average duration of successful tasks during selected interval",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  avg(extract(epoch from finished - last_run))\nFROM\n  timetable.execution_log\nWHERE\n  $__timeFilter(last_run)\n  AND returncode = 0\n  AND client_name in ($client) "
    }
   ]
  },
  {
   "title": "Schedulers running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  0 as time,\n  count(DISTINCT client_name)\nfrom\n  timetable.active_session\n\n"
    }
   ]
  },
  {
   "title": "Task executions (total vs error, selected interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', finished) as time,\n  count(*) as total,\n  count(*) FILTER (WHERE returncode != 0 AND NOT COALESCE(ignore_error, false)) as errors,\n  count(*) FILTER (WHERE returncode != 0 AND ignore_error) as \"ignored errors\"\nFROM\n  timetable.execution_log\nWHERE\n  $__timeFilter(finished) AND client_name in ($client) \nGROUP by\n  1\n"
    }
   ]
  },
  {
   "title": "Task executions errors (selected interval)",
   "type": "table",
   "description": "execution_log.returncode != 0",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  -- $__timeGroup(last_run, $__interval),\n  -- 0 as time,\n  extract(epoch from now() - finished)::int as finished_ago,\n  last_run as started_on,\n  client_name,\n  chain_id,\n  task_id,\n  command,\n  returncode,\n  output\nFROM\n  timetable.execution_log\nWHERE\n  $__timeFilter(last_run)\n  AND returncode != 0 AND NOT ignore_error\nORDER BY\n  finished DESC\nLIMIT\n  50\n  "
    }
   ]
  }
 ]
}